# 데이터셋 전처리 로드

In [ ]:
# 데이터셋 불러오기, 데이터셋 머지

import pandas as pd
import os
import glob

# 폴더경로
folder_path = './data/raw/datalab'

# 제_목적지 검색순위.csv
pattern = os.path.join(folder_path, '*제_목적지 검색순위.csv')
csv_files = glob.glob(pattern)

# 데이터셋 머지
dataframes = []
for file in csv_files:
    try:
        df = pd.read_csv(file, encoding='euc-kr')

        dataframes.append(df)
    except Exception as e:
        print(f"Error reading {file}: {e}")

combined_df = pd.concat(dataframes, ignore_index=True)

print(combined_df)

combined_df.to_csv('Merged_TMAP_SearchRank.csv', index=False)

     읍면동명       목적지명                 도로명주소     카테고리   구분  순위
0     강경읍   논산강경젓갈축제                충남 논산시  기타문화관광지  현지인   1
1     강경읍        강경역                충남 논산시     교통시설  현지인   2
2     강경읍     강경젓갈시장                충남 논산시       시장  현지인   3
3     강경읍        옥녀봉                충남 논산시  자연경관(산)  현지인   4
4     강경읍   강경산소금문학관     충남 논산시 강경포구길 38-0  기타문화관광지  현지인   5
...   ...        ...                   ...      ...  ...  ..
5483  횡성읍    횡성파크골프장    강원 횡성군 앞들동2로 45-19  육상레저스포츠   전체  22
5484  횡성읍        보광사  강원 횡성군 남산로160번길 75-0     종교성지   전체  24
5485  횡성읍    섬강게이트볼장       강원 횡성군 삼일로 93-0  기타레저스포츠   전체  24
5486  횡성읍        광제사     강원 횡성군 입석남1길 38-5     종교성지   전체  26
5487  횡성읍  전통음식휴선체험원  강원 횡성군 태기로개전4길 14-22     기타관광   전체  26

[5488 rows x 6 columns]


In [9]:
# 데이터셋 머지결과확인

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from pathlib import Path
import os

# decimal points
%precision 4
pd.set_option("display.precision",4)

pd.read_csv('Merged_TMAP_SearchRank.csv',encoding='utf-8')
df=pd.read_csv('Merged_TMAP_SearchRank.csv',encoding='utf-8')
df

읍면동명       목적지명                 도로명주소     카테고리   구분  순위
0     강경읍   논산강경젓갈축제                충남 논산시  기타문화관광지  현지인   1
1     강경읍        강경역                충남 논산시     교통시설  현지인   2
2     강경읍     강경젓갈시장                충남 논산시       시장  현지인   3
3     강경읍        옥녀봉                충남 논산시  자연경관(산)  현지인   4
4     강경읍   강경산소금문학관     충남 논산시 강경포구길 38-0  기타문화관광지  현지인   5
...   ...        ...                   ...      ...  ...  ..
5483  횡성읍    횡성파크골프장    강원 횡성군 앞들동2로 45-19  육상레저스포츠   전체  22
5484  횡성읍        보광사  강원 횡성군 남산로160번길 75-0     종교성지   전체  24
5485  횡성읍    섬강게이트볼장       강원 횡성군 삼일로 93-0  기타레저스포츠   전체  24
5486  횡성읍        광제사     강원 횡성군 입석남1길 38-5     종교성지   전체  26
5487  횡성읍  전통음식휴선체험원  강원 횡성군 태기로개전4길 14-22     기타관광   전체  26

[5488 rows x 6 columns]

In [10]:
# df1: '구분' 열의 전체(=현지인+외지인) 데이터를 '미분류_현외'로 교체

import pandas as pd

# 1. CSV 파일 읽어오기
df = pd.read_csv('Merged_TMAP_SearchRank.csv', encoding='utf-8')

# 2. '구분' 열에서 값이 '전체'인 데이터를 '미분류_현외로' 변경
df.loc[df['구분'] == '전체', '구분'] = '미분류_현외'

# 3. 변경된 데이터프레임을 새로운 CSV 파일로 저장
df.to_csv('Merged_TMAP_SearchRank_Rev.csv', index=False, encoding='utf-8')
df

읍면동명       목적지명                 도로명주소     카테고리      구분  순위
0     강경읍   논산강경젓갈축제                충남 논산시  기타문화관광지     현지인   1
1     강경읍        강경역                충남 논산시     교통시설     현지인   2
2     강경읍     강경젓갈시장                충남 논산시       시장     현지인   3
3     강경읍        옥녀봉                충남 논산시  자연경관(산)     현지인   4
4     강경읍   강경산소금문학관     충남 논산시 강경포구길 38-0  기타문화관광지     현지인   5
...   ...        ...                   ...      ...     ...  ..
5483  횡성읍    횡성파크골프장    강원 횡성군 앞들동2로 45-19  육상레저스포츠  미분류_현외  22
5484  횡성읍        보광사  강원 횡성군 남산로160번길 75-0     종교성지  미분류_현외  24
5485  횡성읍    섬강게이트볼장       강원 횡성군 삼일로 93-0  기타레저스포츠  미분류_현외  24
5486  횡성읍        광제사     강원 횡성군 입석남1길 38-5     종교성지  미분류_현외  26
5487  횡성읍  전통음식휴선체험원  강원 횡성군 태기로개전4길 14-22     기타관광  미분류_현외  26

[5488 rows x 6 columns]

# 적합도 검정 2회 실시: 분포가 ~일것이라 가정한 그룹의비율 vs 관측데이터비율 테스트

In [11]:
# 초기가정

# 귀무가설: 외지인과 현지인의 비율은 5:5 일것으로 가정한다(균등분포)
# 대립가설: 외지인과 현지인의 비율은 5:5가 아닐것으로 가정한다(비균등분포)

import numpy as np
import pandas as pd
from scipy.stats import chisquare

# 데이터 로드
df = pd.read_csv('Merged_TMAP_SearchRank_Rev.csv', encoding='utf-8')

# '구분' 열에서 '외지인'과 '현지인'만 필터링
filtered_df = df[df['구분'].isin(['외지인', '현지인'])]

# 관찰값 계산
observed_counts = filtered_df['구분'].value_counts()
observed = observed_counts.values  # 관찰값

# 기대값 계산 (균등 분포: 5:5 비율)
total = sum(observed)
expected = [total * 0.5, total * 0.5]  # 50% 비율로 기대값 계산

# 카이제곱 적합도 검정 수행
chi2_stat, p_value = chisquare(f_obs=observed, f_exp=expected)

# 결과 출력
print("Chi-squared statistic:", chi2_stat)
print("p-value:", p_value)

# 관찰값 및 기대값 확인
print("\nObserved counts:")
print(observed_counts)
print("\nExpected counts (equal distribution 50:50):")
print(expected)

# 귀무가설 기각 여부 판단
alpha = 0.05  # 유의수준 설정
if p_value <= alpha:
    print("\n귀무가설(기각): p_value가 유의수준으로 설정한 0.05보다 유의미하게 작기때문에 현지인과 외지인의 비율은 50:50일 것이라고 가정한다.")
else:
    print("\n귀무가설(선택): p_value가 유의수준으로 설정한 0.05보다 유의미하게 크기때문에 현지인과 외지인의 비율은 50:50가 아닐것으로 가정한다.")

Chi-squared statistic: 76.06108402638371
p-value: 2.7502424246257536e-18

Observed counts:
구분
외지인    2001
현지인    1486
Name: count, dtype: int64

Expected counts (equal distribution 50:50):
[1743.5, 1743.5]

귀무가설(기각): p_value가 유의수준으로 설정한 0.05보다 유의미하게 작기때문에 현지인과 외지인의 비율은 50:50일 것이라고 가정한다.


In [12]:
# 수정가정(시각화결과바탕,최적화(Δ｜예측값-실제값｜:최소값))

# 귀무가설: 외지인과 현지인의 비율은 외지인 0.5736 : 현지인 0.4264 일것으로 가정한다
# 대립가설: 외지인과 현지인의 비율은 외지인 외지인 0.5736 : 현지인 0.4264 아닐것으로 가정한다

import numpy as np
import pandas as pd
from scipy.stats import chisquare

# 데이터 로드
df = pd.read_csv('Merged_TMAP_SearchRank_Rev.csv', encoding='utf-8')

# '구분' 열에서 '외지인'과 '현지인'만 필터링
filtered_df = df[df['구분'].isin(['외지인', '현지인'])]

# 관찰값 계산
observed_counts = filtered_df['구분'].value_counts()
observed = observed_counts.values  # 관찰값

# 기대값 계산 (외지인 57.36%, 현지인 42.64% 비율)
total = sum(observed)
expected = [total * 0.5736, total * 0.4264]  # 57.36%와 42.64% 비율로 기대값 계산

# 카이제곱 적합도 검정 수행
chi2_stat, p_value = chisquare(f_obs=observed, f_exp=expected)

# 결과 출력
print("Chi-squared statistic:", chi2_stat)
print("p-value:", p_value)

# 관찰값 및 기대값 확인
print("\nObserved counts:")
print(observed_counts)
print("\nExpected counts (57.36%:42.64%):")
print(expected)

# 귀무가설 기각 여부 판단
alpha = 0.05  # 유의수준 설정
if p_value <= alpha:
    print("\n대립가설(기각): p_value가 유의수준으로 설정한 0.05보다 유의미하게 작기때문에 외지인과 현지인의 비율은 57.36:42.64가 아니라고 할 수 있습니다.")
else:
    print("\n귀무가설(선택): p_value가 유의수준으로 설정한 0.05보다 유의미하게 크기때문에 외지인과 현지인의 비율은 57.36:42.64라고 할 수 있습니다.")

Chi-squared statistic: 0.0008607571315155046
p-value: 0.9765944917543754

Observed counts:
구분
외지인    2001
현지인    1486
Name: count, dtype: int64

Expected counts (57.36%:42.64%):
[2000.1432, 1486.8568]

귀무가설(선택): p_value가 유의수준으로 설정한 0.05보다 유의미하게 크기때문에 외지인과 현지인의 비율은 57.36:42.64라고 할 수 있습니다.


# 독립성 검정 1회 실시: 행과(카테고리) 열이(검색순위) 서로 영향을 준다
# H₀귀무가설: 카테고리와 검색순위는 관련성이 없다, 독립이다(기각)
# Η₁대립가설: 카테고리와 검색순위는 관련성이 있다, 독립이 아니다(선택)

In [13]:
from scipy.stats import chi2_contingency

# '구분' 열에서 '외지인'과 '현지인'만 필터링
filtered_df = df[df['구분'].isin(['외지인', '현지인'])]

# 교차표 생성
contingency_table = pd.crosstab(filtered_df['카테고리'], filtered_df['순위'])

# 카이제곱 독립성 검정 수행
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# 결과 출력
print(f"Chi-squared statistic: {chi2_stat}")
print(f"p-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print(f"Expected counts:\n{expected}")

# 귀무가설을 기각할지 결정
alpha = 0.05  # 유의수준 0.05 설정

if p_value < alpha:
    print("p_value값이 α값으로 설정한 0.05보다 유의미하게 작기때문에, 귀무가설을 기각합니다. 카테고리 변수와 순위 변수는 독립이 아닙니다.")
else:
    print("p_value값이 α값으로 설정한 0.05보다 유의미하게 크기때문에, 귀무가설을 선택합니다. 카테고리 변수와 순위 변수는 독립 입니다.")

Chi-squared statistic: 2694.6204148288443
p-value: 2.51652967591163e-31
Degrees of freedom: 1891
Expected counts:
[[7.7132e+00 7.6662e+00 7.8073e+00 ... 1.4110e-01 7.9954e-01 5.1735e-01]
 [7.5251e-01 7.4792e-01 7.6169e-01 ... 1.3765e-02 7.8004e-02 5.0473e-02]
 [7.1018e+00 7.0585e+00 7.1884e+00 ... 1.2991e-01 7.3616e-01 4.7634e-01]
 ...
 [1.0723e+01 1.0658e+01 1.0854e+01 ... 1.9616e-01 1.1116e+00 7.1924e-01]
 [8.3717e+00 8.3206e+00 8.4738e+00 ... 1.5314e-01 8.6779e-01 5.6151e-01]
 [2.8219e-01 2.8047e-01 2.8563e-01 ... 5.1620e-03 2.9252e-02 1.8927e-02]]
p_value값이 α값으로 설정한 0.05보다 유의미하게 작기때문에, 귀무가설을 기각합니다. 카테고리 변수와 순위 변수는 독립이 아닙니다.


# Z검정

In [14]:
import pandas as pd

# 데이터 로드
df = pd.read_csv('./Merged_TMAP_SearchRank_Rev.csv', encoding='utf-8')

# '구분' 열의 유니크 값 확인
print(df['구분'].unique())

# '구분' 열에서 '미분류_현외' 값의 행만 선택
unclassified_count = df[df['구분'] == '미분류_현외'].shape[0]

# 비율에 맞게 '현지인'과 '외지인'으로 분할
local_count = int(unclassified_count * 0.4264)  # 현지인 비율
external_count = unclassified_count - local_count  # 외지인 비율

# '미분류_현외' 값을 '현지인'과 '외지인'으로 변경
df.loc[df['구분'] == '미분류_현외', '구분'] = (
    ['현지인'] * local_count + ['외지인'] * external_count
)

# '구분' 열의 값을 다시 확인
print(df['구분'].value_counts())

# 데이터 저장 (원본에 반영 후 저장)
df.to_csv('./Updated_TMAP_SearchRank_Rev.csv', index=False, encoding='utf-8')

# '구분' 열의 수정된 값을 확인
print(df.head())

['현지인' '외지인' '미분류_현외']
구분
외지인    3149
현지인    2339
Name: count, dtype: int64
  읍면동명      목적지명              도로명주소     카테고리   구분  순위
0  강경읍  논산강경젓갈축제             충남 논산시  기타문화관광지  현지인   1
1  강경읍       강경역             충남 논산시     교통시설  현지인   2
2  강경읍    강경젓갈시장             충남 논산시       시장  현지인   3
3  강경읍       옥녀봉             충남 논산시  자연경관(산)  현지인   4
4  강경읍  강경산소금문학관  충남 논산시 강경포구길 38-0  기타문화관광지  현지인   5


In [15]:
# 샘플집단의 비율이 모집단의 비율과 동등한지 Z검정

import pandas as pd
import numpy as np
from scipy import stats
%precision 4
pd.set_option("display.precision",4)

# 데이터 로드
df = pd.read_csv('./Updated_TMAP_SearchRank_Rev.csv', encoding='utf-8')

# 모집단 비율 (현지인 42.64%, 외지인 57.36%)
population_local_ratio = 0.4264
population_external_ratio = 0.5736

# 샘플링을 위한 설정
sample_size = 30  # 각 샘플의 크기

# 샘플링: 샘플을 추출하고 '구분' 열에서 현지인과 외지인의 비율 계산
sample = df['구분'].sample(n=sample_size, replace=True)  # 랜덤 샘플링
sample_local_count = sample.value_counts(normalize=True).get('현지인', 0)
sample_external_count = sample.value_counts(normalize=True).get('외지인', 0)

# 샘플 비율
sample_local_ratio = sample_local_count
sample_external_ratio = sample_external_count

# z-검정을 위한 계산
n = sample_size  # 샘플 크기
p_0 = population_local_ratio  # 모집단의 현지인 비율

# 샘플에서의 현지인 비율을 이용하여 z-검정
z_local = (sample_local_ratio - p_0) / np.sqrt((p_0 * (1 - p_0)) / n)

# p-value 계산 (양측 검정)
p_value_local = 2 * (1 - stats.norm.cdf(abs(z_local)))

# 결과 출력
print(f"Sample Local Ratio: {sample_local_ratio:.4f}")
print(f"Sample External Ratio: {sample_external_ratio:.4f}")
print(f"Z-test for Local: Z = {z_local:.4f}, p-value = {p_value_local:.4f}")

# p-value가 0.05보다 크면 모집단 비율과 차이가 없다고 볼 수 있음
if p_value_local > 0.05:
    print("샘플집단의 local ratio는 모집단의 local ratio와 충분히 다르지 않다")
else:
    print("샘플집단의 local ratio는 모집단의 local ratio와 충분히 다르다")

Sample Local Ratio: 0.5000
Sample External Ratio: 0.5000
Z-test for Local: Z = 0.8151, p-value = 0.4150
샘플집단의 local ratio는 모집단의 local ratio와 충분히 다르지 않다


# +코드1

# +코드 2